### ISSUE TITLE
examples don't work anymore with Transcrypt 3.7

### ISSUE THREAD

**Issue by mjmare** [bunkahle/Transcrypt-Examples#2]
I was happy to find this set of simple examples. Thank you for this.

However, it seems that Transcrypt (3.7.11) has changed its way of including the compiled javascript. It currently generates files in __static__ instead of __javascript__ and it currently it uses constructs like these:
```
<script type="module">import * as hello from './__target__/hello.js'; window.hello = hello;</script>
```
instead of:
```
<script language="javascript" src="__javascript__/hello.js"></script>
```

**Comment by bunkahle** [comment]
yes thank you for the remark. I already updated the README.md file on that and for the time being I would recommend to stay with Transcrypt 3.6 ( pip install transcrypt==3.6 ) since it is has a wider compatibility with browsers as hinted at: https://github.com/QQuick/Transcrypt/issues/611

But of course you can also go with transcrypt 3.7, just change the script line as you have stated above.

**Comment by mjmare** [comment]
OK will do. Thx!
